echo -en "\e[0;104mdocker-images\e[0m = docker images - printing list of all images in system"
echo ""
echo -en "\e[0;104mdocker-containers\e[0m = docker ps -a - printing info of all containers"
echo ""
echo -en "\e[0;104mdocker-runs\e[0m = docker ps - printing info of containres is running"
echo ""
echo -en "\e[0;104mdocker-logs\e[0m = docker logs -f <CONTAINER_NAME> - show log of <CONTAINER_NAME> container right now"
echo ""
echo -en "\e[0;104mdocker-start\e[0m = docker start <CONTAINER_NAME> - starting of <CONTAINER_NAME> container"
echo ""
echo -en "\e[0;104mdocker-stop\e[0m = docker stop <CONTAINER_NAME> - stopping of <CONTAINER_NAME> container"
echo ""
echo -en "\e[0;104mdocker-remove\e[0m = docker rm <CONTAINER_NAME> - removing of <CONTAINER_NAME>"
echo ""
echo -en "\e[0;104mdocker-remove-all-\e[0m = docker rm -f \$(docker ps -aq) - REMOVING ALL CONTAINERS"
echo ""
echo -en "\e[0;104mdocker-info\e[0m = docker inspect <CONTAINER_NAME> - show all information about <CONTAINER_NAME> container"
echo ""
